//--------------------------------------------------------
//
//  L2Diagnostic
//  Author: Mark Stegall
//  Module: RangeCalinfoDock.h
//
//
//  Purpose:
//  display information for a calibration file
//
//  V2.0.0 RC1 2026-08-18
//  V2.0.1  2026-08-24  This is the intial V2.x release
//                      Implemented application of the alpha angle LUT
//                      Added Alpha Angle step size override
//                      Some cleanup of the UI and GUI interactions
//
//--------------------------------------------------------

//--------------------------------------------------------
// GPL-3.0 license
//
// This file is part of L2diagnsotic.
//
// L2diagnsotic is free software : you can redistribute it and /or modify it under
// the terms of the GNU General Public License as published by the Free Software Foundation,
// either version 3 of the License, or (at your option) any later version.
//
// L2diagnsotic is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along with L2diagnsotic.
// If not, see < https://www.gnu.org/licenses/>.
//--------------------------------------------------------
#pragma once

#include <QDockWidget>
#include "L2RangeCorrection.h"

QT_BEGIN_NAMESPACE
namespace Ui {
class RangeCalinfoDock;
}
QT_END_NAMESPACE

//--------------------------------------------------------
// RangaCalinfoDock class definition
//
// This is a dockable window
// ui variables autogenerated from RangaCalinfoDock.ui
//
//--------------------------------------------------------

class RangeCalinfoDock : public QDockWidget
{
    Q_OBJECT

public:
    explicit RangeCalinfoDock(QWidget* parent = nullptr);
    ~RangeCalinfoDock();

    // use these calls to update this dock window
    void updateInfo(const RangeCalibrationInfo& info, bool valid);
    void SetMessage(const std::string& message);

private:
    Ui::RangeCalinfoDock* ui;
};
